language: node_js
node_js:
  - '8.12.0'
cache: yarn
? addons
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.22.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose up -d
  - yarn global add @angular/cli
  - yarn global add codeclimate-test-reporter
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test:ci

after_success:
  - sudo docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - sudo docker tag solteq-assignment-front:latest yokken3122/solteq-assignment-front:latest
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST = "false" ]; then sudo docker push yokken3122/solteq-assignment-front; fi
